#!/usr/bin/python3
from utilities import parseArguments, findRandWithNoZero

args = parseArguments('enc')

keyFilename    = args.k[0]
inputFilename  = args.i[0]
outputFilename = args.o[0]
plaintext = ''

NBits = 0
N     = 0
e     = 0

with open(inputFilename, 'r') as fin:
    plaintext = fin.read().replace('\n','')

with open(keyFilename, 'r') as fin:
    NBits = int(fin.readline())
    N     = int(fin.readline())
    e     = int(fin.readline())

NBytes = int(NBits/8)

# print(f'NBits:{NBits}\nN:{N}\ne:{e}')

rBytes = int(NBytes/2) 
r = findRandWithNoZero(rBytes)

c0 = b'\x00'+b'\x02'+ r + b'\x00' + bytes(plaintext, 'utf-8')
# print('message:', c0)
cint = int.from_bytes(c0, 'big', signed=False)
# print(f'cint: {cint}')
c = pow(cint, e, N) 

with open(outputFilename, 'w+') as fout:
    fout.write(str(c))
